---
development:
  cloud_name: manojdutt
  api_key: '396158358897853'
  api_secret: EIbx4jPKpcz9EXj8fzlQL5afC9A
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: manojdutt
  api_key: '396158358897853'
  api_secret: EIbx4jPKpcz9EXj8fzlQL5afC9A
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: manojdutt
  api_key: '396158358897853'
  api_secret: EIbx4jPKpcz9EXj8fzlQL5afC9A
  enhance_image_tag: true
  static_image_support: false
